2024-10-17 21:32:43,809 INFO    MainThread:13307 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_setup.py:_flush():79] Configure stats pid to 13307
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_setup.py:_flush():79] Loading settings from /Users/bryan.campos/.config/wandb/settings
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_setup.py:_flush():79] Loading settings from /Users/bryan.campos/Documents/Bryan/IA/IA_Proyeto_2/wandb/settings
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'proyecto2.py', 'program_abspath': '/Users/bryan.campos/Documents/Bryan/IA/IA_Proyeto_2/proyecto2.py', 'program': '/Users/bryan.campos/Documents/Bryan/IA/IA_Proyeto_2/proyecto2.py'}
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_init.py:_log_setup():532] Logging user logs to /Users/bryan.campos/Documents/Bryan/IA/IA_Proyeto_2/wandb/run-20241017_213243-f1s0tvs3/logs/debug.log
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_init.py:_log_setup():533] Logging internal logs to /Users/bryan.campos/Documents/Bryan/IA/IA_Proyeto_2/wandb/run-20241017_213243-f1s0tvs3/logs/debug-internal.log
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_init.py:init():617] calling init triggers
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_init.py:init():624] wandb.init called with sweep_config: {}
config: {}
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_init.py:init():667] starting backend
2024-10-17 21:32:43,810 INFO    MainThread:13307 [wandb_init.py:init():671] sending inform_init request
2024-10-17 21:32:43,812 INFO    MainThread:13307 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-10-17 21:32:43,813 INFO    MainThread:13307 [wandb_init.py:init():684] backend started and connected
2024-10-17 21:32:43,818 INFO    MainThread:13307 [wandb_init.py:init():779] updated telemetry
2024-10-17 21:32:43,840 INFO    MainThread:13307 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2024-10-17 21:32:44,046 ERROR   MainThread:13307 [wandb_init.py:init():838] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-17 21:32:44,046 ERROR   MainThread:13307 [wandb_init.py:init():1262] error in wandb.init()
Traceback (most recent call last):
  File "/Users/bryan.campos/Documents/Bryan/IA/IA_Proyeto_2/my_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1252, in init
    return wi.init()
  File "/Users/bryan.campos/Documents/Bryan/IA/IA_Proyeto_2/my_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 844, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-17 21:32:44,275 WARNING MsgRouterThr:13307 [router.py:message_loop():77] message_loop has been closed
